# Development of TechDocs in Backstage is managed by this Kanban board - https://github.com/OrkoHunter/backstage/projects/1
# New issues with TechDocs in their Title or docs-like-code label will be added to the board.

name: Automatically add new TechDocs Issues and PRs to the GitHub project board

on:
  issues:
    types: [opened, reopened, labeled, edited]
  pull_requests:
    types: [opened, reopened, labeled, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_issue_to_project:
    runs-on: ubuntu-latest
    name: Add new issue/PR to the GitHub project board of TechDocs.
    steps:
      - name: Assign new issue/PR to Incoming based on its title.
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.title, 'TechDocs') ||
          contains(github.event.issue.title, 'techdocs') ||
          contains(github.event.issue.title, 'Techdocs')
        with:
          project: 'https://github.com/OrkoHunter/backstage/projects/1'
          column_name: 'Incoming'

      - name: Assign new issue/PR to Incoming based on its label.
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'docs-like-code')
        with:
          project: 'https://github.com/OrkoHunter/backstage/projects/1'
          column_name: 'Incoming'
